language: node_js
node_js:
  - "10"

cache: npm

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      if: branch = master
      before_script: gem install sass
      script: npm run build
      deploy:
        provider: pages
        directory: site
        api_key: $GITHUB_TOKEN
        on:
          branch: master
