language: node_js

cache: npm

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      if: branch = master
      pre_install: gem install sass
      script: npm run build
      deploy:
        provider: pages
        directory: site
        on:
          branch: master
